routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('imprint', 'ImprintController@index');

Route::get('logout', [ 'uses' => 'Auth\LoginController@logout', 'as' => 'logout' ]);
Route::get('/users/{id}/impersonate', 'Auth\LoginController@impersonate')->name('impersonate');
Route::get('/users/stop', 'Auth\LoginController@stopImpersonate');

Route::get('register/successful', 'Auth\RegisterController@showSuccessfulMessage');
Route::get('user/activation/{token}', 'Auth\RegisterController@activateUser')->name('user.activate');

Route::get('shiftlist_public/{day?}', 'PublicShiftlistController@index')->name('public_shiftlist');

Route::group(['namespace' => 'Admin', 'middleware' => ['auth', 'impersonate']], function () {
    Route::get('download/{file}', 'GlobalController@downloadFile')->name('download_file');

    /**
     * News
     */
    Route::get('news', 'News\PostController@index')->name('news_index');

    Route::group(['middleware' => ['role:admin|manager']], function () {
        Route::get('news/{post}/delete', 'News\PostController@delete');
        Route::get('news/comment/{comment}/delete', 'News\CommentController@delete')->name('delete_comment');

        Route::get('news/create', 'News\PostController@create')->name('news_create_post');
        Route::post('news/store', 'News\PostController@store')->name('news_store_post');

        Route::get('news/{post}/edit', 'News\PostController@edit')->name('news_edit_post');
        Route::post('news/{post}/edit', 'News\PostController@update')->name('news_update_post');
        Route::get('news/{post}/edit/file/{file}/delete', 'News\PostController@deleteFile')->name('news_delete_file');
    });

    Route::get('news/{post}', 'News\PostController@details')->name('news_show_comments');
    Route::post('news/{post}', 'News\CommentController@store')->name('news_create_comment');

    Route::group(['middleware' => ['role:admin|manager']], function () {
        Route::get('news/comment/approval', 'News\CommentController@showApprovals')->name('show_approvals');
        Route::get('news/comment/{comment}/approve', 'News\CommentController@approve')->name('approve');
    });

    /**
     * Shiftlist
     */
    Route::get('shiftlist/view/{year?}/{month?}', 'Shiftlist\IndexController@view')->name('shiftlist_view');
    Route::get('shiftlist/{year?}/{month?}', 'Shiftlist\IndexController@index')->name('shiftlist_index');

    /**
     * Settings
     */
    Route::resource('children', 'Settings\ChildrenController');
    Route::resource('closuretimes', 'Settings\ClosuretimesController');
    Route::get('settings', 'Settings\SettingsController@index')->name('settings_index');
    Route::post('settings', 'Settings\SettingsController@save')->name('settings_save');

    /**
     * UserManager
     */
    Route::resource('user', 'UserManager\UserController');
    Route::resource('parent', 'UserManager\ParentController');
    Route::resource('permission', 'UserManager\PermissionController');
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    const KEY_SHIFTLIST_DEFAULT_MORNING_VALUE = 'shiftlist_default_morning_value';
    const KEY_SHIFTLIST_DEFAULT_EVENING_VALUE = 'shiftlist_default_evening_value';

    const DEFAULTS = [
        Setting::KEY_SHIFTLIST_DEFAULT_MORNING_VALUE => '0800',
        Setting::KEY_SHIFTLIST_DEFAULT_EVENING_VALUE => '1700'
    ];

    protected $fillable = ['user_id', 'key', 'value'];

    public static function getDefault($key)
    {
        return array_get(Setting::DEFAULTS, $key, null);
    }
}

app/Http/Controllers/Admin/Settings/ChildrenController.php
<?php

namespace App\Http\Controllers\Admin\Settings;

use App\Models\Child;
use App\Models\NurseryBuilding;
use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ChildrenController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:parentsettings-access');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $children = Auth::user()->children;

        return view('admin.settings.children.index')->with(compact('children'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $buildings = NurseryBuilding::with('groups')->get();

        return view('admin.settings.children.create')->with(compact('buildings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'firstname' => 'required|max:255',
            'lastname' => 'required|max:255',
            'group' => 'required|exists:nursery_groups,id',
        ], [
            'firstname.required' => 'Bitte geben Sie den Vorname Ihres Kindes ein',
            'firstname.max' => 'Bitte geben Sie den Vorname Ihres Kindes ein',
            'lastname.required' => 'Bitte geben Sie den Nachnamen Ihres Kindes ein',
            'lastname.max' => 'Bitte geben Sie den Nachnamen Ihres Kindes ein',
            'group.required' => 'Bitte wählen Sie eine Gruppe aus',
            'group.exists' => 'Bitte wählen Sie eine Gruppe aus'
        ]);

        Child::create([
            'firstname' => request('firstname'),
            'lastname' => request('lastname'),
            'nursery_group_id' => request('group'),
            'user_id' => Auth::user()->id
        ]);

        return redirect()->route('children.index')->with('success', 'Kind erfolgreich angelegt');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $buildings = NurseryBuilding::with('groups')->get();
        $child = Child::find($id);

        if ($child->user_id != Auth::user()->id) {
            return response('Sie können dieses Kind nicht bearbeiten!', 404);
        }

        return view('admin.settings.children.edit')->with(compact('buildings', 'child'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'firstname' => 'required|max:255',
            'lastname' => 'required|max:255',
            'group' => 'required|exists:nursery_groups,id',
        ], [
            'firstname.required' => 'Bitte geben Sie den Vorname Ihres Kindes ein',
            'firstname.max' => 'Bitte geben Sie den Vorname Ihres Kindes ein',
            'lastname.required' => 'Bitte geben Sie den Nachnamen Ihres Kindes ein',
            'lastname.max' => 'Bitte geben Sie den Nachnamen Ihres Kindes ein',
            'group.required' => 'Bitte wählen Sie eine Gruppe aus',
            'group.exists' => 'Bitte wählen Sie eine Gruppe aus'
        ]);

        $child = Child::find($id);

        if ($child->user_id != Auth::user()->id) {
            return response('Sie können dieses Kind nicht bearbeiten!', 404);
        }

        $child->firstname = request('firstname');
        $child->lastname = request('lastname');
        $child->nursery_group_id = request('group');
        $child->save();

        return redirect()->route('children.index')->with('success', 'Kind erfolgreich geändert');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $child = Child::find($id);

        if ($child->user_id != Auth::user()->id) {
            return response('Sie können dieses Kind nicht bearbeiten!', 404);
        }

        $child->delete();

        return redirect()->route('children.index')->with('success', 'Kind erfolgreich gelöscht');
    }
}

app/Http/Controllers/Admin/Settings/ClosuretimesController.php
<?php

namespace App\Http\Controllers\Admin\Settings;

use App\Models\Child;
use App\Models\ClosureTime;
use App\Models\NurseryBuilding;
use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;

class ClosuretimesController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:closuretimes-access');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $closuretimes = ClosureTime::whereYear('from', '>=', date("Y"))->get();

        return view('admin.settings.closuretimes.index')->with(compact('closuretimes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.settings.closuretimes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'from' => 'required|date',
            'to' => 'date',
            'type' => 'required|in:'.ClosureTime::TYPE_FULL_DAY_CLOSED.','.ClosureTime::TYPE_MORNING_CLOSED,
        ], [
            'from.required' => 'Bitte geben Sie ein Startdatum ein',
            'from.date' => 'Bitte geben Sie ein gültiges Startdatum ein',
            'to.date' => 'Bitte geben Sie ein gültiges Enddatum ein',
            'type.required' => 'Bitte wählen Sie einen Typ aus',
            'type.in' => 'Bitte wählen Sie einen Typ aus'
        ]);

        ClosureTime::create([
            'from' => strtotime(request('from')),
            'to' => strtotime(request('to')),
            'type' => request('type')
        ]);

        return redirect()->route('closuretimes.index')->with('success', 'Schließzeit erfolgreich angelegt');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    /**
     * @param $id
     *
     * @return View
     */
    public function edit($id)
    {
        $closuretime = ClosureTime::find($id);

        return view('admin.settings.closuretimes.edit')->with(compact('closuretime'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'from' => 'required|date',
            'to' => 'date',
            'type' => 'required|in:'.ClosureTime::TYPE_FULL_DAY_CLOSED.','.ClosureTime::TYPE_MORNING_CLOSED,
        ], [
            'from.required' => 'Bitte geben Sie ein Startdatum ein',
            'from.date' => 'Bitte geben Sie ein gültiges Startdatum ein',
            'to.date' => 'Bitte geben Sie ein gültiges Enddatum ein',
            'type.required' => 'Bitte wählen Sie einen Typ aus',
            'type.in' => 'Bitte wählen Sie einen Typ aus'
        ]);

        $closuretime = ClosureTime::find($id);

        $closuretime->from = strtotime(request('from'));
        $closuretime->to = strtotime(request('to'));
        $closuretime->type = request('type');
        $closuretime->save();

        return redirect()->route('closuretimes.index')->with('success', 'Schließzeit erfolgreich geändert');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $entry = ClosureTime::find($id);
        $entry->delete();

        return redirect()->route('closuretimes.index')->with('success', 'Schließzeit erfolgreich gelöscht');
    }
}

app/Http/Controllers/Admin/Settings/SettingsController.php
<?php

namespace App\Http\Controllers\Admin\Settings;

use App\Http\Requests\SaveSettings;
use App\Models\Child;
use App\Models\NurseryBuilding;
use App\Models\Setting;
use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingsController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:parentsettings-access');
    }

    public function index()
    {
        return view('admin.settings.settings.index');
    }

    public function save(SaveSettings $saveSettings)
    {
        $settings_to_set = array_only($saveSettings->all(), array_keys(Setting::DEFAULTS));

        foreach ($settings_to_set as $key => $value) {
            Auth::user()->settings()->updateOrCreate(
                ['key' => $key],
                ['value' => $value]
            );
        }

        return redirect()->route('settings_index')->with('success', 'Einstellungen gespeichert');
    }
}

resources/views/admin/settings/children/create.blade.php
@extends('layouts.app_admin')

@section('head')
    <style>

    </style>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item active">Ihre Kinder</li>
    </ol>
@endsection

@section('content')
    <h1 class="h2">Kind hinzufügen</h1>

    <div class="card">
        <div class="card-block">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif


            <form method="post" action="{{ route('children.store') }}">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="name">Vorname:</label>
                            <input class="form-control" name="firstname" id="firstname" placeholder="" value="{{ old('firstname') }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="name">Nachname:</label>
                            <input class="form-control" name="lastname" id="lastname" placeholder="" value="{{ old('lastname') }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        <label for="group">Gruppe:</label>
                        <select class="form-control" name="group" id="group">
                            <option value="">Bitte auswählen</option>
                            @foreach($buildings as $building)
                                <optgroup label="{{ $building->description }}">
                                    @foreach($building->groups as $group)
                                        <option value="{{ $group->id }}" {{ (old('group') == $group->id) ? 'selected="selected"' : '' }}>{{ $group->description }}</option>
                                    @endforeach
                                </optgroup>
                            @endforeach
                        </select>
                    </div>
                </div>
                {{ csrf_field() }}
                <button type="submit" class="btn btn-primary">Speichern</button>
                <p class="text-muted m-t-2">
                    Hinweis: Die Kita-Leitung wird über das Anlegen neuer Kinder informiert!
                </p>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/settings/children/edit.blade.php
@extends('layouts.app_admin')

@section('head')
    <style>

    </style>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item active">Ihre Kinder</li>
    </ol>
@endsection

@section('content')
    <h1 class="h2">Kind bearbeiten</h1>
    <div class="card">
        <div class="card-block">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form method="post" action="{{ route('children.update', $child) }}">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="name">Vorname:</label>
                            <input class="form-control" name="firstname" id="firstname" placeholder="" value="{{ old('firstname', $child->firstname) }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="name">Nachname:</label>
                            <input class="form-control" name="lastname" id="lastname" placeholder="" value="{{ old('lastname', $child->lastname) }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-12">
                        <label for="group">Gruppe:</label>
                        <select class="form-control" name="group" id="group">
                            <option value="">Bitte auswählen</option>
                            @foreach($buildings as $building)
                                <optgroup label="{{ $building->description }}">
                                    @foreach($building->groups as $group)
                                        <option value="{{ $group->id }}" {{ (old('group', $child->nursery_group_id) == $group->id) ? 'selected="selected"' : '' }}>{{ $group->description }}</option>
                                    @endforeach
                                </optgroup>
                            @endforeach
                        </select>
                    </div>
                </div>
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <button type="submit" class="btn btn-primary">Speichern</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/settings/children/index.blade.php
@extends('layouts.app_admin')

@section('head')
    <style>

    </style>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item active">Ihre Kinder</li>
    </ol>
@endsection

@section('content')
    <h1 class="h2">Ihre Kinder</h1>

    <div class="card">
        <div class="card-block">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif

            <table class="table table-bordered table-sm vmiddle" id="childlist">
                <thead>
                    <tr>
                        <th>Vorname</th>
                        <th>Nachname</th>
                        <th>Gruppe</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($children as $child)
                    <tr>
                        <td>{{ $child->firstname }}</td>
                        <td>{{ $child->lastname }}</td>
                        <td>{{ $child->nursery_group->description }} ({{ $child->nursery_group->building->description }})</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="{{ route('children.edit', $child) }}"><i class="fa fa-pencil"></i></a>
                            <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#myModal" data-id="{{ $child->id }}"><i class="fa fa-trash"></i></button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            <a class="btn btn-success" href="{{ route('children.create') }}" id="add_child"><i class="icon-plus"></i> &nbsp;Kind hinzufügen</a>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h5 class="modal-title" id="myModalLabel">Kind wirklich löschen?</h5>
                </div>
                <div class="modal-footer">
                    <form method="post" action="" id="deleteForm">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
                        <button type="submit" class="btn btn-danger">Ja, löschen</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        var delete_url = '{{ route('children.destroy', 'USERID') }}';
        $('#myModal').on('show.bs.modal', function (e) {
            $('#deleteForm').attr('action', delete_url.replace('USERID', $(e.relatedTarget).attr('data-id')));
        })
    </script>
@endsection