routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('imprint', 'ImprintController@index');

Route::get('logout', [ 'uses' => 'Auth\LoginController@logout', 'as' => 'logout' ]);
Route::get('/users/{id}/impersonate', 'Auth\LoginController@impersonate')->name('impersonate');
Route::get('/users/stop', 'Auth\LoginController@stopImpersonate');

Route::get('register/successful', 'Auth\RegisterController@showSuccessfulMessage');
Route::get('user/activation/{token}', 'Auth\RegisterController@activateUser')->name('user.activate');

Route::get('shiftlist_public/{day?}', 'PublicShiftlistController@index')->name('public_shiftlist');

Route::group(['namespace' => 'Admin', 'middleware' => ['auth', 'impersonate']], function () {
    Route::get('download/{file}', 'GlobalController@downloadFile')->name('download_file');

    /**
     * News
     */
    Route::get('news', 'News\PostController@index')->name('news_index');

    Route::group(['middleware' => ['role:admin|manager']], function () {
        Route::get('news/{post}/delete', 'News\PostController@delete');
        Route::get('news/comment/{comment}/delete', 'News\CommentController@delete')->name('delete_comment');

        Route::get('news/create', 'News\PostController@create')->name('news_create_post');
        Route::post('news/store', 'News\PostController@store')->name('news_store_post');

        Route::get('news/{post}/edit', 'News\PostController@edit')->name('news_edit_post');
        Route::post('news/{post}/edit', 'News\PostController@update')->name('news_update_post');
        Route::get('news/{post}/edit/file/{file}/delete', 'News\PostController@deleteFile')->name('news_delete_file');
    });

    Route::get('news/{post}', 'News\PostController@details')->name('news_show_comments');
    Route::post('news/{post}', 'News\CommentController@store')->name('news_create_comment');

    Route::group(['middleware' => ['role:admin|manager']], function () {
        Route::get('news/comment/approval', 'News\CommentController@showApprovals')->name('show_approvals');
        Route::get('news/comment/{comment}/approve', 'News\CommentController@approve')->name('approve');
    });

    /**
     * Shiftlist
     */
    Route::get('shiftlist/view/{year?}/{month?}', 'Shiftlist\IndexController@view')->name('shiftlist_view');
    Route::get('shiftlist/{year?}/{month?}', 'Shiftlist\IndexController@index')->name('shiftlist_index');

    /**
     * Settings
     */
    Route::resource('children', 'Settings\ChildrenController');
    Route::resource('closuretimes', 'Settings\ClosuretimesController');
    Route::get('settings', 'Settings\SettingsController@index')->name('settings_index');
    Route::post('settings', 'Settings\SettingsController@save')->name('settings_save');

    /**
     * UserManager
     */
    Route::resource('user', 'UserManager\UserController');
    Route::resource('parent', 'UserManager\ParentController');
    Route::resource('permission', 'UserManager\PermissionController');
});

app/Models/Permission.php
<?php

namespace App\Models;

use Laratrust\LaratrustPermission;

class Permission extends LaratrustPermission
{
    protected $fillable = ['name', 'display_name', 'description'];
}

app/Http/Controllers/Admin/UserManager/ParentController.php
<?php

namespace App\Http\Controllers\Admin\UserManager;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\DataTables\ParentDataTable;
use App\Http\Controllers\Controller;

class ParentController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:parentmanager-access');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ParentDataTable $dataTable)
    {
        return $dataTable->render('admin.usermanager.parent.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::where('name', '!=', 'admin')->get();

        return view('admin.usermanager.parent.edit')->with(compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = request('name');
        $user->email = request('email');
        $user->confirmed = ($request->has('confirmed') && request('confirmed') == 1);
        $user->activated = ($request->has('activated') && request('activated') == 1);
        $user->save();

        $user->roles()->detach();

        $role_ids = request('roles');
        if (is_array($role_ids) && count($role_ids) > 0) {
            Role::find($role_ids)->each(function ($role) use ($user) {
                $user->attachRole($role);
            });
        }

        return redirect()->route('parent.index')->with('success', 'User erfolgreich geändert');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('user.index')->with('success', 'User erfolgreich gelöscht');
    }
}

app/Http/Controllers/Admin/UserManager/PermissionController.php
<?php

namespace App\Http\Controllers\Admin\UserManager;

use App\DataTables\UsersDataTable;
use App\Models\Permission;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PermissionController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:usermanager-access');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::with('roles')->get();

        return view('admin.usermanager.permission.index')->with(compact('permissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = Permission::find($id);
        $roles = Role::all();

        return view('admin.usermanager.permission.edit')->with(compact('permission', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $permission = Permission::find($id);
        $permission->name = request('name');
        $permission->display_name = request('display_name');
        $permission->description = request('description');
        $permission->save();

        $permission->roles()->detach();

        $role_ids = request('roles');
        if (is_array($role_ids) && count($role_ids) > 0) {
            Role::find($role_ids)->each(function ($role) use ($permission) {
                $role->attachPermission($permission);
            });
        }

        return redirect()->route('permission.index')->with('success', 'Berechtigung erfolgreich geändert');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();

        return view('admin.usermanager.permission.create')->with(compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'display_name' => 'required|string|max:255',
            'description' => 'string|max:255',
        ]);

        $permission = Permission::create($request->all());

        $role_ids = request('roles');
        if (is_array($role_ids) && count($role_ids) > 0) {
            Role::find($role_ids)->each(function ($role) use ($permission) {
                $role->attachPermission($permission);
            });
        }

        return redirect()->route('permission.index')->with('success', 'Berechtigung erfolgreich angelegt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $permission = Permission::find($id);
        $permission->delete();

        return redirect()->route('permission.index')->with('success', 'Berechtigung erfolgreich gelöscht');
    }
}

app/Http/Controllers/Admin/UserManager/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManager;

use App\DataTables\UsersDataTable;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:usermanager-access');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(UsersDataTable $dataTable)
    {
        return $dataTable->render('admin.usermanager.user.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::all();

        return view('admin.usermanager.user.edit')->with(compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = request('name');
        $user->email = request('email');
        $user->confirmed = ($request->has('confirmed') && request('confirmed') == 1);
        $user->activated = ($request->has('activated') && request('activated') == 1);
        $user->save();

        $user->roles()->detach();

        $role_ids = request('roles');
        if (is_array($role_ids) && count($role_ids) > 0) {
            Role::find($role_ids)->each(function ($role) use ($user) {
                $user->attachRole($role);
            });
        }

        return redirect()->route('user.index')->with('success', 'User erfolgreich geändert');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('user.index')->with('success', 'User erfolgreich gelöscht');
    }
}

resources/views/admin/usermanager/permission/create.blade.php
@extends('layouts.app_admin')

@section('head')
    <style>

    </style>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('user.index') }}">Benutzerverwaltung</a></li>
        <li class="breadcrumb-item"><a href="{{ route('permission.index') }}">Berechtigungsverwaltung</a></li>
        <li class="breadcrumb-item active">Neue Berechtigung</li>
    </ol>
@endsection

@section('content')
    <div class="card">
        <div class="card-block">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif

            <form method="post" action="{{ route('permission.store') }}">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input class="form-control" name="name" id="name" placeholder="" value="{{ old('name') }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="display_name">Anzeigename:</label>
                            <input class="form-control" name="display_name" id="display_name" placeholder="" value="{{ old('display_name') }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="description">Beschreibung:</label>
                            <input class="form-control" name="description" id="description" placeholder="" value="{{ old('description') }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="roles">Rollen:</label>
                            <div class="form-group">
                                @foreach($roles as $role)
                                    <label for="role_{{ $role->id }}" class="checkbox-inline">
                                        <input name="roles[]" id="role_{{ $role->id }}" value="{{ $role->id }}" type="checkbox" {{ (in_array($role->id, old('roles', []))) ? 'checked' : '' }}>
                                        {{ $role->display_name }}
                                    </label>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>

                {{ csrf_field() }}
                <button type="submit" class="btn btn-primary">Speichern</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/usermanager/permission/edit.blade.php
@extends('layouts.app_admin')

@section('head')
    <style>

    </style>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('user.index') }}">Benutzerverwaltung</a></li>
        <li class="breadcrumb-item"><a href="{{ route('permission.index') }}">Berechtigungsverwaltung</a></li>
        <li class="breadcrumb-item active">Berechtigung bearbeiten</li>
    </ol>
@endsection

@section('content')
    <div class="card">
        <div class="card-block">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif

            <form method="post" action="{{ route('permission.update', $permission) }}">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input class="form-control" name="name" id="name" placeholder="" value="{{ old('name', $permission->name) }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="display_name">Anzeigename:</label>
                            <input class="form-control" name="display_name" id="display_name" placeholder="" value="{{ old('display_name', $permission->display_name) }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="description">Beschreibung:</label>
                            <input class="form-control" name="description" id="description" placeholder="" value="{{ old('description', $permission->description) }}" type="text">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="roles">Rollen:</label>
                            <div class="form-group">
                                @foreach($roles as $role)
                                    <label for="role_{{ $role->id }}" class="checkbox-inline">
                                        <input name="roles[]" id="role_{{ $role->id }}" value="{{ $role->id }}" type="checkbox" {{ (in_array($role->id, old('roles', $permission->roles->pluck('id')->toArray()))) ? 'checked' : '' }}>
                                        {{ $role->display_name }}
                                    </label>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>

                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <button type="submit" class="btn btn-primary">Speichern</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/usermanager/permission/index.blade.php
@extends('layouts.app_admin')

@section('head')
    <style>

    </style>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('user.index') }}">Benutzerverwaltung</a></li>
        <li class="breadcrumb-item active">Berechtigungsverwaltung</li>
        <li class="breadcrumb-menu">
            <div class="btn-group" role="group" aria-label="">
                <a class="btn btn-success" href="{{ route('permission.create') }}"><i class="icon-plus"></i> &nbsp;Neue Berechtigung</a>
            </div>
        </li>
    </ol>
@endsection

@section('content')
    <div class="card">
        <div class="card-block">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif

            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Anzeige-Name</th>
                        <th>Beschreibung</th>
                        <th>Rolle(n)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($permissions as $permission)
                    <tr>
                        <td>{{ $permission->name }}</td>
                        <td>{{ $permission->display_name }}</td>
                        <td>{{ $permission->description }}</td>
                        <td>{{ $permission->roles->implode('display_name', ', ') }}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="{{ route('permission.edit', $permission) }}"><i class="fa fa-pencil"></i></a>
                            <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#myModal" data-id="{{ $permission->id }}"><i class="fa fa-trash"></i></button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h5 class="modal-title" id="myModalLabel">Berechtigung wirklich löschen?</h5>
                </div>
                <div class="modal-footer">
                    <form method="post" action="" id="deleteForm">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
                        <button type="submit" class="btn btn-danger">Ja, löschen</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        var delete_url = '{{ route('permission.destroy', 'ITEMID') }}';
        $('#myModal').on('show.bs.modal', function (e) {
            $('#deleteForm').attr('action', delete_url.replace('ITEMID', $(e.relatedTarget).attr('data-id')));
        })
    </script>
@endsection